services:
  postgres:
    image: ankane/pgvector:latest   # includes pgvector preinstalled
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql

  pgweb:
    container_name: pgweb_helper
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres  # my database container is called postgres, not db
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/db?sslmode=disable
    depends_on:
      - postgres
